/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppWorkflowsRouteImport } from './routes/app/workflows'
import { Route as AppTemplatesRouteImport } from './routes/app/templates'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppProjectsRouteImport } from './routes/app/projects'
import { Route as AppMarketplaceRouteImport } from './routes/app/marketplace'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppWorkflowsIndexRouteImport } from './routes/app/workflows.index'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects.index'
import { Route as AppWorkflowsWorkflowIdRouteImport } from './routes/app/workflows.$workflowId'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app/projects.$projectId'
import { Route as AppBlocksBlockIdRouteImport } from './routes/app/blocks.$blockId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppWorkflowsWorkflowIdRoute = AppWorkflowsWorkflowIdRouteImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppBlocksBlockIdRoute = AppBlocksBlockIdRouteImport.update({
  id: '/blocks/$blockId',
  path: '/blocks/$blockId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/workflows': typeof AppWorkflowsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/blocks/$blockId': typeof AppBlocksBlockIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/workflows/': typeof AppWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/app/login': typeof AppLoginRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app': typeof AppIndexRoute
  '/app/blocks/$blockId': typeof AppBlocksBlockIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/workflows': typeof AppWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/workflows': typeof AppWorkflowsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/blocks/$blockId': typeof AppBlocksBlockIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/workflows/': typeof AppWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/app/login'
    | '/app/marketplace'
    | '/app/projects'
    | '/app/settings'
    | '/app/templates'
    | '/app/workflows'
    | '/app/'
    | '/app/blocks/$blockId'
    | '/app/projects/$projectId'
    | '/app/workflows/$workflowId'
    | '/app/projects/'
    | '/app/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app/login'
    | '/app/marketplace'
    | '/app/settings'
    | '/app/templates'
    | '/app'
    | '/app/blocks/$blockId'
    | '/app/projects/$projectId'
    | '/app/workflows/$workflowId'
    | '/app/projects'
    | '/app/workflows'
  id:
    | '__root__'
    | '/app'
    | '/app/login'
    | '/app/marketplace'
    | '/app/projects'
    | '/app/settings'
    | '/app/templates'
    | '/app/workflows'
    | '/app/'
    | '/app/blocks/$blockId'
    | '/app/projects/$projectId'
    | '/app/workflows/$workflowId'
    | '/app/projects/'
    | '/app/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflows': {
      id: '/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflows/': {
      id: '/app/workflows/'
      path: '/'
      fullPath: '/app/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/workflows/$workflowId': {
      id: '/app/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/app/workflows/$workflowId'
      preLoaderRoute: typeof AppWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/blocks/$blockId': {
      id: '/app/blocks/$blockId'
      path: '/blocks/$blockId'
      fullPath: '/app/blocks/$blockId'
      preLoaderRoute: typeof AppBlocksBlockIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppWorkflowsRouteChildren {
  AppWorkflowsWorkflowIdRoute: typeof AppWorkflowsWorkflowIdRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
}

const AppWorkflowsRouteChildren: AppWorkflowsRouteChildren = {
  AppWorkflowsWorkflowIdRoute: AppWorkflowsWorkflowIdRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
}

const AppWorkflowsRouteWithChildren = AppWorkflowsRoute._addFileChildren(
  AppWorkflowsRouteChildren,
)

interface AppRouteChildren {
  AppLoginRoute: typeof AppLoginRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppWorkflowsRoute: typeof AppWorkflowsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppBlocksBlockIdRoute: typeof AppBlocksBlockIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLoginRoute: AppLoginRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppWorkflowsRoute: AppWorkflowsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppBlocksBlockIdRoute: AppBlocksBlockIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
